version: 0.2

phases:
  build:
    commands:
       - echo Start installing and building
       - npm ci && npm run build # clean install (npm ci) and build (npm run build)
       - echo End installing and building

artifacts:
  files:
    - '**/*'