services:
  server:
    container_name: dev-social-server
    build:
      dockerfile: Dockerfile
      context: .
      target: development # Only will build development stage from dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # workaround to fix bcrypt issue
    env_file:
      - .env.docker
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: dev-social-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
    driver: local
